Less plugin
pankod/next-cli-core-plugins pull request #15
Opened 2021-01-13 13:46 UTC by burcukaragozzz

2021-01-13 13:57 UTC, omeraplak commented
@burcukaragozzz example'ını bunun gibi yapabilirsin;
https://github.com/pankod/next-cli-core-plugins/blob/master/plugins/sass/src/Components/Sass/index.tsx
bunun less versiyonu

2021-01-13 14:01 UTC, burcukaragozzz commented
> @burcukaragozzz example'ını bunun gibi yapabilirsin;
> https://github.com/pankod/next-cli-core-plugins/blob/master/plugins/sass/src/Components/Sass/index.tsx
> bunun less versiyonu

evet evet bende öyle yapıyorum

2021-01-13 14:51 UTC, burcukaragozzz commented
next config'e müdahale etmek çok doğru olmadı sanırım ama her yerde öyle yapmışlar @aliemir ile de konuştuk sonradan düzeltilmesi gerekebilirmiş çakışma olmasın diye @omeraplak @yildirayunlu 

kaynak: 
https://nextjs.org/docs/basic-features/built-in-css-support
https://github.com/vercel/next-plugins/tree/master/packages/next-less

2021-01-13 14:59 UTC, omeraplak commented
@burcukaragozzz o zaman bence şöyle yapalım,
https://github.com/nuxt/create-nuxt-app/blob/master/packages/cna-template/template/nuxt/nuxt.config.js

template dosyası içinde if yazıp eğer less seçildiyse plugin'i eklesin.

next plugin'leri de yönetmek için,
https://github.com/cyrilwanner/next-compose-plugins bu paketi template'e ekleyebiliriz

2021-01-14 09:35 UTC, omeraplak requested changes

2021-01-14 09:35 UTC, omeraplak commented on prompt.js
> +                { message: "LESS", name: "less"}
```suggestion
                { message: "None", name: "none"},
                { message: "Sass/Scss", name: "sass" },
                { message: "Less", name: "less"}
```

diğer prompt'lar ile uyumlu olması için bu şekilde yapalım

2021-01-14 09:37 UTC, yildirayunlu commented on plugins/less/src/Components/Less/styles.less
> +  .card--header {
BEM yazıyorsak bunlar `__`olmalı.

2021-01-14 09:37 UTC, yildirayunlu commented on plugins/less/src/Components/Less/index.tsx
> +import css from "./styles.less";
Tüm plugin'lerde uyumluluk olması açısından bu şekilde olsa iyi olur.

`import styles from "./index.less";`

2021-01-14 09:39 UTC, yildirayunlu commented on prompt.js
> +                { message: "NONE", name: "none"},
```suggestion
                { message: "None", name: "none"},
```

2021-01-14 09:40 UTC, yildirayunlu commented on prompt.js
> +                { message: "LESS", name: "less"}
Belki bunları da bu şekilde yazabiliriz? @omeraplak @aliemir @burcukaragozzz 
```suggestion
                { message: "Sass", name: "sass" },
                { message: "Less", name: "less"}
```

2021-01-14 09:41 UTC, omeraplak commented on prompt.js
> +                { message: "LESS", name: "less"}
benim önerim şı şekilde,
  { message: "None", name: "none"},
                { message: "Sass/Scss", name: "sass" },
                { message: "Less", name: "less"}

2021-01-14 09:41 UTC, yildirayunlu commented on prompt.js
> +                { message: "LESS", name: "less"}
Duplucate https://github.com/pankod/next-cli-core-plugins/pull/15#discussion_r557259194

2021-01-14 09:41 UTC, yildirayunlu commented on prompt.js
> +                { message: "NONE", name: "none"},
Duplucate https://github.com/pankod/next-cli-core-plugins/pull/15#discussion_r557259194

2021-01-14 10:27 UTC, omeraplak approved these changes

2021-01-14 10:33 UTC, yildirayunlu approved these changes

2021-01-14 10:40 UTC, merged